name: build-and-push-ghcr

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag image yang mau dipush (contoh: latest, v1.0.0, test). Kosong = auto (latest + sha)"
        required: false
        default: ""
      push_latest:
        description: "Also push :latest"
        type: boolean
        required: false
        default: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # ghcr.io/<owner>/<repo>

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags
        id: tags
        shell: bash
        run: |
          IMAGE="${REGISTRY}/${IMAGE_NAME}"
          TAG_INPUT="${{ github.event.inputs.tag }}"
          PUSH_LATEST="${{ github.event.inputs.push_latest }}"
          SHA_TAG="sha-${GITHUB_SHA::7}"

          TAGS="${IMAGE}:${SHA_TAG}"

          if [ -n "${TAG_INPUT}" ]; then
            TAGS="${TAGS},${IMAGE}:${TAG_INPUT}"
          fi

          if [ "${PUSH_LATEST}" = "true" ]; then
            TAGS="${TAGS},${IMAGE}:latest"
          fi

          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Build & Push (amd64 + arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
